# Generated by Django 3.1.4 on 2020-12-11 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='creator',
            new_name='creator_id',
        ),
        migrations.RenameField(
            model_name='userlogged',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, null=True)),
                ('vertical', models.CharField(max_length=255, null=True)),
                ('items', models.CharField(max_length=2000, null=True)),
                ('privacy', models.CharField(max_length=40)),
                ('img_link', models.CharField(max_length=1000, null=True)),
                ('url', models.CharField(max_length=1000, null=True)),
                ('coords', models.CharField(max_length=255, null=True)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
            ],
        ),
    ]
