# Generated by Django 3.1.4 on 2020-12-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201211_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='userlogged',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
